name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup old build files
        run: rm -rf ./build || true  # Adjust the directory based on your project structure

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        env:
          GOOGLE_API_KEY: ${{ AIzaSyAU8dBB-H49p1YHV0Y5_01AXZiO2gjATFE }}
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ AIzaSyAU8dBB-H49p1YHV0Y5_01AXZiO2gjATFE }}
          publish_dir: ./
          keep_files: false  # Ensure no old files are kept to prevent conflicts
          cname: ''  # Set CNAME to empty if you are not using a custom domain
